---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template deploys an ECS cluster to the provided VPC and subnets
  using an Auto Scaling Group.

Parameters:

  AppName:
    Description: >
      This will be app name
    Type: String

  Environment:
    Description: >
      This points out which environment is used.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
    ConstraintDescription: >
      Must be one of the defined allowed values.

  CustomAmiId:
    Description: Baked custom ami id
    Type: String

Resources:

  BastionNode:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-bastion
      ImageId: !Ref CustomAmiId
      InstanceType: t2.micro
      SubnetId:
        !Select
          - 0
          - Fn::Split:
            - ","
            - Fn::ImportValue:
                !Sub hb-tracking-cluster-public-subnets-list-${AWS::Region}-${Environment}
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      KeyName: artur.siepietowski.pub
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${AppName}-${Environment}-bastion-host-security-group-id-${AWS::Region}
