version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - IMAGE_URI_LATEST="${REPOSITORY_URI}:latest"
  build:
    commands:
      - docker build --tag $IMAGE_URI --tag $IMAGE_URI_LATEST drf_ecs/
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"drf_ecs","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
